pi/pi: pi/pi.o
	mpicc pi/pi.o -o pi/pi

pi/pi.o: 
	mpicc -c pi/pi.c -lm 

avg/avg: avg/avg.o
	mpicc avg/avc.o -o avg/avg

avg/avg.o: 
	mpicc -c avg/avg.c -lm 

primes/primes: primes/primes.o
	mpicc primes/primes.o -o primes/primes

primes/primes.o: 
	mpicc -c primes/primes.c -lm 